name:                bitcoin-taro
version:             0.1.0.0
github:              "tochicool/bitcoin-taro"
license:             BSD3
author:              "Tochi Obudulu"
maintainer:          "tochicool@gmail.com"
copyright:           "2022 Tochi Obudulu"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Bitcoin TARO library for Haskell
category:            Bitcoin, Finance

description:         Please see the README on GitHub at <https://github.com/tochicool/bitcoin-taro#readme>

data-files:
- test/vectors/*

dependencies:
- base >= 4.7 && < 5
- basement
- binary
- bitcoin
- bytestring
- containers
- cryptonite
- memory
- mtl
- text
- vector

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  bitcoin-taro-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bitcoin-taro

tests:
  bitcoin-taro-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - bitcoin-taro
    - hedgehog
    - hspec
    - tasty
    - tasty-hedgehog >= 1.2 && < 1.3
    - tasty-hspec
    - tasty-hunit
    - text

    - pretty-simple
    - base16

build-tools:
  tasty-discover:tasty-discover
